//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationProject.AccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.IAccountWebService")]
    public interface IAccountWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/Create", ReplyAction="http://tempuri.org/IAccountWebService/CreateResponse")]
        bool Create(DTO.Account user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/Create", ReplyAction="http://tempuri.org/IAccountWebService/CreateResponse")]
        System.Threading.Tasks.Task<bool> CreateAsync(DTO.Account user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/ValidateIdentityUser", ReplyAction="http://tempuri.org/IAccountWebService/ValidateIdentityUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO.Account))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO.BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO.CustomerLoginResults))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO.Student))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<DTO.Student>))]
        DTO.IdentityLoginResult ValidateIdentityUser(string username, string password, bool shouldLockout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/ValidateIdentityUser", ReplyAction="http://tempuri.org/IAccountWebService/ValidateIdentityUserResponse")]
        System.Threading.Tasks.Task<DTO.IdentityLoginResult> ValidateIdentityUserAsync(string username, string password, bool shouldLockout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/CreateIdentity", ReplyAction="http://tempuri.org/IAccountWebService/CreateIdentityResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO.Account))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO.BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO.IdentityLoginResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO.CustomerLoginResults))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO.Student))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<DTO.Student>))]
        System.Security.Claims.ClaimsIdentity CreateIdentity(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/CreateIdentity", ReplyAction="http://tempuri.org/IAccountWebService/CreateIdentityResponse")]
        System.Threading.Tasks.Task<System.Security.Claims.ClaimsIdentity> CreateIdentityAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/GetSecurityStamp", ReplyAction="http://tempuri.org/IAccountWebService/GetSecurityStampResponse")]
        string GetSecurityStamp(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/GetSecurityStamp", ReplyAction="http://tempuri.org/IAccountWebService/GetSecurityStampResponse")]
        System.Threading.Tasks.Task<string> GetSecurityStampAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/IdentityUserExistsById", ReplyAction="http://tempuri.org/IAccountWebService/IdentityUserExistsByIdResponse")]
        bool IdentityUserExistsById(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/IdentityUserExistsById", ReplyAction="http://tempuri.org/IAccountWebService/IdentityUserExistsByIdResponse")]
        System.Threading.Tasks.Task<bool> IdentityUserExistsByIdAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/SupportsUserSecurityStamp", ReplyAction="http://tempuri.org/IAccountWebService/SupportsUserSecurityStampResponse")]
        bool SupportsUserSecurityStamp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/SupportsUserSecurityStamp", ReplyAction="http://tempuri.org/IAccountWebService/SupportsUserSecurityStampResponse")]
        System.Threading.Tasks.Task<bool> SupportsUserSecurityStampAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/CreateStudent", ReplyAction="http://tempuri.org/IAccountWebService/CreateStudentResponse")]
        void CreateStudent(DTO.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/CreateStudent", ReplyAction="http://tempuri.org/IAccountWebService/CreateStudentResponse")]
        System.Threading.Tasks.Task CreateStudentAsync(DTO.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/GetAllStudentsByUsername", ReplyAction="http://tempuri.org/IAccountWebService/GetAllStudentsByUsernameResponse")]
        System.Collections.Generic.List<DTO.Student> GetAllStudentsByUsername(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountWebService/GetAllStudentsByUsername", ReplyAction="http://tempuri.org/IAccountWebService/GetAllStudentsByUsernameResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DTO.Student>> GetAllStudentsByUsernameAsync(string UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountWebServiceChannel : AuthenticationProject.AccountService.IAccountWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountWebServiceClient : System.ServiceModel.ClientBase<AuthenticationProject.AccountService.IAccountWebService>, AuthenticationProject.AccountService.IAccountWebService {
        
        public AccountWebServiceClient() {
        }
        
        public AccountWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Create(DTO.Account user, string password) {
            return base.Channel.Create(user, password);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAsync(DTO.Account user, string password) {
            return base.Channel.CreateAsync(user, password);
        }
        
        public DTO.IdentityLoginResult ValidateIdentityUser(string username, string password, bool shouldLockout) {
            return base.Channel.ValidateIdentityUser(username, password, shouldLockout);
        }
        
        public System.Threading.Tasks.Task<DTO.IdentityLoginResult> ValidateIdentityUserAsync(string username, string password, bool shouldLockout) {
            return base.Channel.ValidateIdentityUserAsync(username, password, shouldLockout);
        }
        
        public System.Security.Claims.ClaimsIdentity CreateIdentity(string userId) {
            return base.Channel.CreateIdentity(userId);
        }
        
        public System.Threading.Tasks.Task<System.Security.Claims.ClaimsIdentity> CreateIdentityAsync(string userId) {
            return base.Channel.CreateIdentityAsync(userId);
        }
        
        public string GetSecurityStamp(string userId) {
            return base.Channel.GetSecurityStamp(userId);
        }
        
        public System.Threading.Tasks.Task<string> GetSecurityStampAsync(string userId) {
            return base.Channel.GetSecurityStampAsync(userId);
        }
        
        public bool IdentityUserExistsById(string userId) {
            return base.Channel.IdentityUserExistsById(userId);
        }
        
        public System.Threading.Tasks.Task<bool> IdentityUserExistsByIdAsync(string userId) {
            return base.Channel.IdentityUserExistsByIdAsync(userId);
        }
        
        public bool SupportsUserSecurityStamp() {
            return base.Channel.SupportsUserSecurityStamp();
        }
        
        public System.Threading.Tasks.Task<bool> SupportsUserSecurityStampAsync() {
            return base.Channel.SupportsUserSecurityStampAsync();
        }
        
        public void CreateStudent(DTO.Student student) {
            base.Channel.CreateStudent(student);
        }
        
        public System.Threading.Tasks.Task CreateStudentAsync(DTO.Student student) {
            return base.Channel.CreateStudentAsync(student);
        }
        
        public System.Collections.Generic.List<DTO.Student> GetAllStudentsByUsername(string UserID) {
            return base.Channel.GetAllStudentsByUsername(UserID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DTO.Student>> GetAllStudentsByUsernameAsync(string UserID) {
            return base.Channel.GetAllStudentsByUsernameAsync(UserID);
        }
    }
}
